PROJECT_NAME = Bank
TEST_PROJ_NAME = Test_$(PROJECT_NAME)
SRC = src/PrintDetails.c\
src/RegisterAccount.c\
src/SearchAccount.c\
src/SortAccount.c\
src/Transaction.c\
src/WriteFile.c

INC_H = inc


run:
	gcc -I $(INC_H) $(SRC) main.c -o $(PROJECT_NAME).exe